---
title: Ex-13
date: 2025-04-21
author: Your Name
cell_count: 7
score: 5
---

```python
#created at 20250415
```


```python
#MEthod Chaining
```


```python
print("\n === Method Chaining ===")
```

    
     === Method Chaining ===



```python
class Calculator:
    def __init__(self):
        self.result = 0

    def add(Self, n):
        self.result += n
        return self

    def multipy(self, n):
        self.result *= n
        return self

    def get_result(self):
        return self.result
```


```python
calc = Calculator()
```


```python
print(calc.add(5).multiply(2).add(3).get_result())
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    Cell In[5], line 1
    ----> 1 print(calc.add(5).multiply(2).add(3).get_result())


    Cell In[2], line 6, in Calculator.add(Self, n)
          5 def add(Self, n):
    ----> 6     self.result += n
          7     return self


    NameError: name 'self' is not defined



```python

```


---
**Score: 5**