---
title: Ex-5-3953
date: 2025-04-26
author: Your Name
cell_count: 9
score: 5
---

```python
#created at 20250307
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/2.-asynchronous-programming
```


```python
#Producer consumer pattern
```


```python
import asyncio
```


```python
async def producer(queue):
    for i in range(5):
        print(f"Producing{i}")
        await queue.put(i)
        await asyncio.sleep(1)
```


```python
async def consumer(queue):
    while True:
        item = await queue.get()
        print(f"consuming{item}")
        queue.task_done()
```


```python
async def main():
    queue = asyncio.Queue()
    await asyncio.gather(producer(queue), consumer(queue))
    
```


```python
asyncio.run(main())
```


    ---------------------------------------------------------------------------

    RuntimeError                              Traceback (most recent call last)

    Cell In[9], line 1
    ----> 1 asyncio.run(main())


    File ~/miniconda3/envs/py312/lib/python3.12/asyncio/runners.py:190, in run(main, debug, loop_factory)
        161 """Execute the coroutine and return the result.
        162 
        163 This function runs the passed coroutine, taking care of
       (...)
        186     asyncio.run(main())
        187 """
        188 if events._get_running_loop() is not None:
        189     # fail fast with short traceback
    --> 190     raise RuntimeError(
        191         "asyncio.run() cannot be called from a running event loop")
        193 with Runner(debug=debug, loop_factory=loop_factory) as runner:
        194     return runner.run(main)


    RuntimeError: asyncio.run() cannot be called from a running event loop



```python

```


---
**Score: 5**