---
title: Ex-7-4409
date: 2025-04-29
author: Your Name
cell_count: 10
score: 10
---

```python
#created at 20250308
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/2.-asynchronous-programming
```


```python
#Asynchronous File I/O wit aiofiles
```


```python
import aiofiles
```


```python
import asyncio
```


```python
async def write_to_file():
    async with aiofiles.open("example.txt","w") as f:
        await f.write("Hello,async file I/O!\n)
    
```


      Cell In[5], line 3
        await f.write("Hello,async file I/O!\n)
                      ^
    SyntaxError: unterminated string literal (detected at line 3)




```python
async def read_from_file():
    async with aiofiles.open("example.txt","r") as f:
        content = await f.read()
        print(content)
```


```python
async def main():
    await write_to_file()
    await raed_from_file()
```


```python
asyncio.run(main())
```


    ---------------------------------------------------------------------------

    RuntimeError                              Traceback (most recent call last)

    Cell In[8], line 1
    ----> 1 asyncio.run(main())


    File ~/miniconda3/envs/py312/lib/python3.12/asyncio/runners.py:190, in run(main, debug, loop_factory)
        161 """Execute the coroutine and return the result.
        162 
        163 This function runs the passed coroutine, taking care of
       (...)
        186     asyncio.run(main())
        187 """
        188 if events._get_running_loop() is not None:
        189     # fail fast with short traceback
    --> 190     raise RuntimeError(
        191         "asyncio.run() cannot be called from a running event loop")
        193 with Runner(debug=debug, loop_factory=loop_factory) as runner:
        194     return runner.run(main)


    RuntimeError: asyncio.run() cannot be called from a running event loop



```python

```


---
**Score: 10**