---
title: Ex-8-7094
date: 2025-04-29
author: Your Name
cell_count: 8
score: 5
---

```python
#created at 20250308
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/2.-asynchronous-programming
```


```python
#using asyncio.semaphore to Limit concurrency
```


```python
import asyncio
```


```python
async def limited_tast(sem,i):
    async with sem:
        print(f"first tast  starting{i}")
        asyncio.sleep(2)
        print(f"first task {i}done")
```


```python
async def main():
    sem = asyncio.semaphore(2)
    tasks = [limited_task(sem, i) for i in range(5)]
    await asyncio.gather(*tasks)
```


```python
asyncio.run(main())
```


    ---------------------------------------------------------------------------

    RuntimeError                              Traceback (most recent call last)

    Cell In[4], line 1
    ----> 1 asyncio.run(main())


    File ~/miniconda3/envs/py312/lib/python3.12/asyncio/runners.py:190, in run(main, debug, loop_factory)
        161 """Execute the coroutine and return the result.
        162 
        163 This function runs the passed coroutine, taking care of
       (...)
        186     asyncio.run(main())
        187 """
        188 if events._get_running_loop() is not None:
        189     # fail fast with short traceback
    --> 190     raise RuntimeError(
        191         "asyncio.run() cannot be called from a running event loop")
        193 with Runner(debug=debug, loop_factory=loop_factory) as runner:
        194     return runner.run(main)


    RuntimeError: asyncio.run() cannot be called from a running event loop



```python

```


---
**Score: 5**