---
title: Ex-8-8821
date: 2025-04-29
author: Your Name
cell_count: 7
score: 5
---

```python
#created at 20250314
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/10.-mocking-in-unit-tests
```


```python
#Mocking a context Manager
```


```python
from unittest.mock import MagicMock
```


```python
mock_context =  MagicMock
mock_context.__enter__.return_value = "Inside the context"
mock_context.__exit__.return_value = none
```


    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    Cell In[4], line 2
          1 mock_context =  MagicMock
    ----> 2 mock_context.__enter__.return_value = "Inside the context"
          3 mock_context.__exit__.return_value = none


    AttributeError: type object 'MagicMock' has no attribute '__enter__'



```python
with mock_context as value:
    print(value)
```


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    Cell In[5], line 1
    ----> 1 with mock_context as value:
          2     print(value)


    TypeError: 'type' object does not support the context manager protocol



```python

```


---
**Score: 5**