---
title: Ex-2-5944
date: 2025-04-26
author: Your Name
cell_count: 7
score: 5
---

```python
#created at 20250315
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/14.-custom-exceptions
```


```python
#custom exception with custom message
```


```python
class InvalidAgeError(Exception):
    def __init__(self, age, message = "Age must greater than 0"):
        self.age = age
        self.message = message
        super().__init__(self.message)
```


```python
def validate_age(age):
    if age <= 0:
        raise InvalideAgeError(age)
        print(f"age {age} is valid")
```


```python
try:
    validate_age(0)
except InvalidAgeError as e:
    print(f"Error {e}")
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    Cell In[3], line 2
          1 try:
    ----> 2     validate_age(0)
          3 except InvalidAgeError as e:
          4     print(f"Error {e}")


    Cell In[2], line 3, in validate_age(age)
          1 def validate_age(age):
          2     if age <= 0:
    ----> 3         raise InvalideAgeError(age)
          4         print(f"age {age} is valid")


    NameError: name 'InvalideAgeError' is not defined



```python

```


---
**Score: 5**